Repository startersclan/hlstatsx-community-edition, pull requests merged in 2025-02, with the labels that each got.

#66 Fix (daemon): Fix Dockerfile.daemon installation of mysql client libraries
  Dockerfile.daemon
Labels: fix

#59 Fix: Fix bugs in daemon and web
  src/scripts/TRcon.pm
  src/scripts/hlstats.pl
  src/web/includes/functions.php
  src/web/pages/ingame/accuracy.php
  src/web/pages/ingame/actioninfo.php
  src/web/pages/ingame/mapinfo.php
  src/web/pages/ingame/motd.php
  src/web/pages/ingame/targets.php
  src/web/pages/ingame/weapons.php
  src/web/pages/ventrilostatus.php
  src/web/sig.php
Labels: fix

#68 Fix (web): Fix bugs in some pages
  src/web/autocomplete.php
  src/web/pages/actioninfo.php
  src/web/pages/ingame/actioninfo.php
  src/web/pages/teamspeak.php
  src/web/pages/ventrilo.php
  src/web/pages/ventrilostatus.php
  src/web/status.php
  src/web/trend_graph.php
Labels: fix

#69 Fix (development): Fix xdebug path mapping
  .vscode/launch.json
Labels: fix

#67 Enhancement (tests): Add tests for all web routes
  test/test-routes.sh
Labels: enhancement

#70 Chore: Release 1.11.4
  .github/release-drafter.yml
  README.md
  docker-compose.example.yml
  src/sql/install.sql
  src/web/updater/89.php
Labels: chore
